### ISSUE TITLE
Events (change, added, remove) are not working correctly

### ISSUE THREAD

**Issue by flozzel** [gridstack/gridstack.js#1118] opened 2020-01-17 14:31 UTC
## Subject of the issue
I am trying to use the provided events to detect changes on my dashboard.
For example, I have created the following event handler to detect changes and trigger the saving procedure:

```javascript
this.$dashboard.on( 'removed', $.proxy( this.save, this ) );
```

This triggers this save method:

```javascript
save()
  {
    let items = this.serialize();
    let number = this.$dashboard.data( 'number' );
    let date = dashboardApp.dateString;

    $.ajax({
      url: "ajax/save.php",
      method: 'post',
      data: { name: 'items', value: items, number: number, date: date }
    })
    .done( function( result )
    {
      //console.log( result );
    });
  }
```

Now to my problem: When I am using the "changed" event to detect changes on my dashboard, it triggers the event for the dashboard to which the item was dropped, but not for the dashboard from which the item was removed. I also tried to use a combination of several events: 

- "changed" if the order of the items has been changed on the same dashboard
- "added" if an item was dropped to the dashboard which then also should trigger:
- "removed" when an item was removed from one dashboard to another

The "added" event seems to trigger reliable, the "changed" for items moved on the same dashboard too, but for items removed from one dashboard just as the "removed" event it does not trigger every time it should do.

Also when the "removed" event triggered, then it appears to be before the item was removed from the previous dashboard to the new one. Because at the time the event triggers and I initiate my saving process, in the DOM the item is still allocated to the previous dashboard.

My serialization method is simple and works like this:

```javascript
serialize()
  {
    let items = [];

    this.$dashboard.children( '.grid-stack-item' ).each( function( index, element )
    {
      let $element = $( element );

      items[ index ] =
      {
        id: $element.data( 'id' ),
        type: $element.data( 'type' ),
        x: $element.data( 'gs-x' ),
        y: $element.data( 'gs-y' )
      };

    });

    return items;
  }
```

And this returns the dashboards items in the following format:

```json
[
  {
    "id": 52,
    "type": "vehicles",
    "x": 0,
    "y": 0
  },
  {
    "id": 2,
    "type": "employees",
    "x": 0,
    "y": 1
  },
  {
    "id": 13,
    "type": "employees",
    "x": 0,
    "y": 2
  }
]
```

## Your environment
gridstack.js 0.6.0-dev
Mozilla Firefox 72.0.1 (64-Bit)

## Steps to reproduce
I can provide a test environment of my project to the devs, it is running with an older version of gridstack but the problem is also existing there. I already send the login details to Dylan in the past, relating to another issue. Please let me know if some of you also need access or something other to provide.

**Comment by adumesny** [comment] 2020-01-18 20:59
> Now to my problem: When I am using the "changed" event to detect changes on my dashboard, it triggers the event for the dashboard to which the item was dropped, but not for the dashboard from which the item was removed

please use 0.6.0 as I re-wrote how we call events (much less frequent and correct items now).

using the https://gridstackjs.com/demo/two.html demo open the log (clear it) and drag one item from one grid to the other and you will get correct event.

grid1 removed 1 items. (x,y)=4,0
grid2 added 1 items. (x,y)=0,3
grid2 change 1 items. (x,y)=0,3

closing this unless you can provide running code showing issue in the lib. I added loggin to many demos to make sure we get correct events now,

**Comment by flozzel** [comment] 2020-01-20 14:38
@adumesny 
I tested it in the demos, there is everything working as expected.

Also I changed my gridstack version from 0.6.0-dev to 0.6.0 and tried it, but same problem too.
Here is a short clip of me showing the problem:

![gridstack_issue](https://user-images.githubusercontent.com/33422121/72733889-16656400-3b99-11ea-9779-88cc8e31c445.gif)

I have a test environment running, for security reasons I can not make it available for public so I will send you the access details via mail.

**Comment by adumesny** [comment] 2020-01-20 17:03
confusing as you use "displosition 5" for "dashboard 4" (make the number the same).
it would be great to see the placeholder shadow to see what's going on as I suspect you get TWO of them when placing those wide items between two grids, and one is left behind when dropped - which is a known issue and could create weird placement issues...

![image](https://user-images.githubusercontent.com/3496166/72744923-6295b180-3b63-11ea-8118-bbb166e24234.png)

I can't be debugging your code, so please create a test showing issue (see https://jsfiddle.net/adumesny/jqhkry7g)

Also, looks like you are creating 14 grids ? maybe you should use nested grids and let only sub-item be dragged between them - see https://gridstackjs.com/demo/nested.html

**Comment by flozzel** [comment] 2020-01-31 13:05
Sorry for the late answer.

I forgot to mention, that there are a some crazy things going on regarding to the movement of the items. I already opened a issue about this and I have not been able to solve it yet.

https://github.com/gridstack/gridstack.js/issues/1020

The numbering of the dashboards is a little bit confusing, but the number you see in the console is the number (index) I am using for saving, loading etc. and commonly the index starts at zero.

For the dashboard I am using 14 seperate grids. The nested grids would have the charm that you could move the individual grids between each other, but for that I would have to change the current structure of my code. And if it is not necesscary, I would like to avoid that.
Or do you see any problems creating 14 seperate grids?

I am not able to recreate the problem, maybe you can take a look at my code in the test environment. I created you a FTP access for this and send you a mail about the details.

**Comment by adumesny** [comment] 2020-01-31 18:56
thanks, but like I said I don't have the bandwidth to debug people's code (unless you want to hire me :)
so unless you can reproduce in a simple app, I won't be able to take a look.

**Comment by flozzel** [comment] 2020-02-03 11:16
Okay sorry, this should not come across like an impolite prompt to debug my code.
I am glad somebody's helping me at all :)

I will try to reproduce the problem somehow in a jsfiddle and then I will let you know.

**Comment by flozzel** [comment] 2020-10-06 16:19
**Update:** I think I can reproduce the problem now with version 2.0.0

When moving an item from one dashboard to another while going over other dashboards with items, which move thereby, the remove event is not triggerd every time.

I have a short clip again of me visualizing the problem. On the first time I am just moving an item from the sidebar without touching the others. In the console you can see, how as first the removed and then the added event triggerd - so the way it should be.

On the second and the third time, I am moving items from the sidebar while going over already used dashboards and the existing items moving. I could imagine, the change event which is triggered for moving items could cause this ( I am just not giving it out to console here ).

![gridstack-issue_06_10_20](https://user-images.githubusercontent.com/33422121/95228613-dbc35a80-07ff-11eb-898a-9ee2c9347626.gif)

While it still works properly the second time, it is not at the third time. When I have tried it before, I could reproduce it three times in a row this way.

It would be nice, if you maybe could take a look at this again.

**Comment by adumesny** [comment] 2020-10-06 18:57
the 3rd time you appear to be moving the item out FAST vs the other cases, wondering if related to #1183 ?
I seem to recall seeing a drag-out timer and maybe you are running into this issue ?

**Comment by flozzel** [comment] 2020-10-07 13:18
I tested it, and it seems that moving the items fast is making the problem occur more often.
But sometimes it also happens when moving the item slow, but not so frequently.

If you move it very fast, it sometimes even happens that the item gets stuck like this:

![gridstack-issue_07_10_20](https://user-images.githubusercontent.com/33422121/95323658-cfdaa580-089e-11eb-8656-f86cb7bd5d29.PNG)

Sometimes when the items overlap, then in combination with this it also often happens that only the added event is triggered.
This then looks like this (here are the events working correct):

![Viaplano-Mozilla-Firefox-2020-10-07-13-01-25](https://user-images.githubusercontent.com/33422121/95335515-cad22200-08af-11eb-9f76-f7b5391dea0a.gif)

I also tried the "removeTime: 0" option like mentioned in the other thread, but it unfortunately changes nothing in this behavior.

**Comment by adumesny** [comment] 2020-10-07 15:18
you mean `removeTimeout` option. it still calls `setTimeout(0)` and therefore change the behavior, but I don't know (yet) why there is a timeout.
You **could** try overriding `_setupRemovingTimeout()` to do nothing and see if it changes behavior. I bet it will.

```js
GridStack.prototype._setupRemovingTimeout= function() {return this};
```

**Comment by flozzel** [comment] 2020-10-07 16:39
Yes sorry, I meant removeTimeout of course and tried it with this option.

I also have tried to override the function. But unfortunately again I cannot see any change.
I have overwritten it as follows (right after the library was included):

```javascript

//.....

<script src="libraries/js/gridstack.all.js"></script>

<script type="application/javascript">
      GridStack.prototype._setupRemovingTimeout= function(){return this};
</script>

//.....

```

**Comment by adumesny** [comment] 2020-10-07 17:59
put a consol log in there and make sure your versions is actually being used. don't have other suggestions at this point.

**Comment by flozzel** [comment] 2020-10-08 14:57
Added a console.log before the return in my overloaded function as well into the original function in the library.
But the function doesn't even seems to be called.

**Comment by adumesny** [comment] 2020-10-08 23:10
> gridstack.js 0.6.0-dev

are you using 0.6.x ? you need to try the latest (2.0.2) otherwise I can't help you. look at conversion docs as API changes 1.x, then get back to me.

**Comment by flozzel** [comment] 2020-10-12 15:40
No, I was using version 2.0.0, but have updated to 2.0.2 now.

**Comment by adumesny** [comment] 2020-11-02 05:25
I can't debug without a reproduceable test case. Closing until you provide a simple jsfiddle or similar....

**Closed by adumesny** 2020-11-02 05:25 UTC

**Comment by flozzel** [comment] 2020-12-07 11:27
I never expected to experience this day, but everything is working fine now. I am using the 3.0.0 with gridstack-h5.js and have no problems anymore. No overlapping items, no strangely behaving items and no more problems with non triggering events.

Maybe it was simply a problem with jQueryUI..

**Comment by adumesny** [comment] 2020-12-07 15:40
glad to hear that! the html5 and v3 was quite a re-write of things... make sure to donate if you find the lib useful!
