### ISSUE TITLE
Items overlap and move unexpectedly

### ISSUE THREAD

**Issue by dslinnard** [gridstack/gridstack.js#812] opened 2017-11-03 17:20 UTC
Items overlap and move unexpectedly
<img width="659" alt="screen shot 2017-11-03 at 11 26 05 am" src="https://user-images.githubusercontent.com/9345703/32387029-90182abc-c099-11e7-81cd-6e2aa64347ab.png">
<img width="721" alt="screen shot 2017-11-03 at 11 26 17 am" src="https://user-images.githubusercontent.com/9345703/32387038-959dffde-c099-11e7-8120-c0ca6c8fb3e1.png">
<img width="770" alt="screen shot 2017-11-03 at 11 26 26 am" src="https://user-images.githubusercontent.com/9345703/32387045-9a6eb30a-c099-11e7-908d-d78b9a8b7016.png">

gridstack.js 0.3.0
Mac OS 
10.12.6 Chrome and Firefox

Using this fiddle https://jsfiddle.net/dslinnard/xmtj8rrb/
1) Move block 3 to the right of block 1 leaving enough space for block 2 between them.
2) Move block 2 between block 1 and block 3

## Expected behaviour
I would expect block 6 to remain where it was at the bottom

## Actual behaviour
You will see block 6 move beneath blocks 2 and 3

I have attached some screenshots in the correct order above. Thank you for all your hard work in this project. I'm hoping I have made a simple mistake but after a few hours I cannot figure it out.

**Comment by DoesntMatter** [comment] 2017-11-05 16:24
Can confirm weird grid item alignments on version 0.3.0.
I used a "float"ing grid and got overlapping items while dragging, especially if there are items on the bottom of the page.

In version 0.2.7-dev everything works as intended and I was not able to reproduce this behavior.
Tested with following commit:
https://github.com/gridstack/gridstack.js/tree/eebc0b15a6a7e18790c33417c56eae9aee995fc3

**Comment by dslinnard** [comment] 2017-11-05 21:29
Thank you DoesntMatter, will try out with 0.2.7 until the issue is fixed in a future version.

**Comment by tomdagz** [comment] 2017-11-13 16:12
the same thing happened to me. new version is gonna solved this issue??

**Comment by akansal1** [comment] 2017-11-15 09:55
you may refer #766 , discussing something similar in my opinion

**Comment by radiolips** [comment] 2018-02-12 16:11
@dslinnard have you tried using the `develop` branch? I'm curious to know if it's currently fixed on `1.0.0-dev`.

**Comment by dslinnard** [comment] 2018-02-14 00:04
Checking now

**Comment by dslinnard** [comment] 2018-02-14 00:20
Yes it does fix it and a fiddle using V1.0 dev can be found here https://jsfiddle.net/dslinnard/u4r2082s/12/

**Comment by radiolips** [comment] 2018-02-14 01:43
@dslinnard Great! If you're able to, you can use that branch for now. I'm going to close this ticket out, since it's resolved in 1.0-dev. If you have any problems, reopen this issue and let me know.

**Closed by radiolips** 2018-02-14 01:43 UTC
