### ISSUE TITLE
Items are overlapping or disappearing when moving from one grid to another FAST

### ISSUE THREAD

**Issue by felippe-regazio** [gridstack/gridstack.js#1183] opened 2020-03-04 14:51 UTC
## Subject of the issue

Items are overlapping or disappearing when moving from one grid to another.
I recorded a video:

https://drive.google.com/file/d/1a-3sVLhvuIrPqUS-sgFNT5yK8Txys9TL/view?usp=sharing

## Your environment
* using the demo on the plugin webpage
* Chrome Version 80.0.3987.122 (Official Build) (64-bit) on Ubuntu 18 LTS

## Steps to reproduce

Drop an item from one grid to another

## Expected behaviour

The item should be allocated on the other grid without break, disappear or overlap other items

## Actual behaviour

The new item sometimes break the order, disappear or overlap another items

**Comment by adumesny** [comment] 2020-03-04 18:22
weird!
I'm not able to reproduce this from the same https://gridstackjs.com/demo/two.html 
I see you have moved the items from their default initial values - does it happen otherwise?  (I tried as well).

I'm also running chrome 80.0.3987.122 but on windows10

have you tried other browsers or machines, and is there something (like speed) that makes it happen ?

need to narrow it down further. thank you.

**Comment by felippe-regazio** [comment] 2020-03-04 18:49
Yea, very weird haha.

I was talking with a friend of mine now, and we noted something:
You need to move an item from one grid to another fastly.
So, for sure its relationated to how fast you move an item from one grid to another.

We are guessing that, when you move an item from one grid to another quickly, the gridstack doesnt have time enough to calculate the placeholder and alocate the new, leading to this weird behaviors and droping the item randomly.

This doenst happen when moving items on same grid, but when moving from one grid to another, the original position is irrelevant, the problem happens anyway.

**Comment by adumesny** [comment] 2020-03-04 19:11
you need less coffee  my friend!

**Comment by adumesny** [comment] 2020-03-08 15:37
wondering if setting `removeTimeout: 0` as grid option solves this issue for you ? I have a hunch it might.

**Comment by felippe-regazio** [comment] 2020-03-09 12:36
We tested and the problem persists.

**Comment by adumesny** [comment] 2020-12-03 17:16
closing as likely gone in 3.0 with h5 drag&drop. re-open if still exist.

**Closed by adumesny** 2020-12-03 17:16 UTC
Labels: status:need more info
