### ISSUE TITLE
Disable animation on init

### ISSUE THREAD

**Issue by bad-shape-guy** [gridstack/gridstack.js#2496] opened 2023-10-09 10:08 UTC
Good afternoon, I recently updated my version from a fairly old one to a new one, and noticed that now when the page is initialized, it's as if all the widgets are in zero coordinates and move to their place with animation

Here you can observe this effect:
https://gridstackjs.com/demo/nested.html

Of course you can disable it with the "animate" parameter, but in this way all animation will be disabled, when dragging, resizing, etc.

The feeling that this did not happen before, i.e. there was animation when moving and changing, but it was not there when initializing, and all widgets were immediately in their place when loading

Please tell me how you can solve my problem. Thanks

**Comment by adumesny** [comment] 2023-10-09 17:18
yeah  noticed that as well recently. not sure when it started...

**Comment by bad-shape-guy** [comment] 2023-10-10 06:55
I think the problem is between releases 8.1.0 and 8.1.1

`.grid-stack > .grid-stack-item {
  position: absolute;
  top: 0px;
  left: 0%;
  padding: 0;
}`

Attributes **top** and **left** break the display of widgets

**Comment by adumesny** [comment] 2023-10-11 17:34
8.1.1 had a tons of CSS changes #2315 and likely side affect - thankas for narrowing it down thge build #

**Comment by JakubEleniuk** [comment] 2023-11-04 12:57
Can be fixed by removing this line https://github.com/gridstack/gridstack.js/blob/599965a3e921772192b24628fef00f7420991ff4/src/gridstack.scss#L132

**Comment by adumesny** [comment] 2023-11-05 15:10
no that removes the entire animation for everything. the problem is on init - maybe fix is to delay setting animation style on the grid until after init... not sure what 8.1.1 change broke this.

**Comment by adumesny** [comment] 2023-11-11 17:40
fixed in next release. don't forget to donate if you find this lib useful!

**Closed** 2023-11-11 17:39 UTC
Labels: type:bug
