### ISSUE TITLE
9 item grid not working

### ISSUE THREAD

**Issue by lxlxs** [gridstack/gridstack.js#1958] opened 2022-04-28 14:02 UTC
## 9 item grid not working
I have a grid with the target to have 9 items, it has 3 rows and 3 columns. Everything works fine with a bit of extra work but i have one problem. If i want to add my 9th item, i cant do that, because of the placeholder, that means i must have the option to disable the placeholder for placeing my last item. 

Is there any option to do that or do i need an extra field?
Unfortunately i cant provide a view of the project, because its for a client

**Comment by adumesny** [comment] 2022-04-28 18:13
how are you adding that last item ? dragging it in (where the placeholder would appear) should work because that it used to place the item and shouldn't count as a real item, or are you trying to move it around while adding it ?

you need to create a simple demo showing the issue if you want me to even think of taking a look... start with one of the demos and bug template.

**Comment by adumesny** [comment] 2022-06-14 20:33
closing due to non reproduceable example...

**Closed by adumesny** 2022-06-14 20:33 UTC
Labels: status:need more info
