### ISSUE TITLE
[Error On Save]: Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rafalsk** [gridstack/gridstack.js#1860] opened 2021-10-02 12:46 UTC
We're facing a problem when serializing the entire container of nested items.
The error is: "Uncaught RangeError: Maximum call stack size exceeded" 

We were investigating it when all of the sudden we noticed that the very same error is reproducible in the Demo of your own  :-)

https://gridstackjs.com/demo/nested.html

When clicking the 'save' button, the error is exactly the same, visible below.

![image](https://user-images.githubusercontent.com/9338163/135716743-16eb9d2a-bb97-49e9-9433-a25b720e402a.png)

Great MIT licensed library you've got! We're incorporating it into GRIDNET OS (https://gridnet.org)

**Comment by adumesny** [comment] 2021-10-02 15:29
Oops, something broke recently ! thanks.

**Comment by borgmajr** [comment] 2021-10-02 21:35
I too just ran in to this exact bug and came to the same conclusion. Is there a safe version to roll back to for saving nested children or will this get fixed fast enough to just hang on? Thanks! P.S> I am really enjoying gridstack.js so far as I use it in my prototype.

**Comment by adumesny** [comment] 2021-10-03 15:07
this was caused by fix for #1793 - fix should be coming shortly...

**Comment by adumesny** [comment] 2021-10-03 15:30
fixed in next release. don't forget to donate if you find this lib useful!

**Closed** 2021-10-03 15:29 UTC
Labels: type:bug, severity:important
