### ISSUE TITLE
Resizing horizontally stretches intro wrong direction

### ISSUE THREAD

**Issue by riccardolardi** [gridstack/gridstack.js#1731] opened 2021-04-14 10:03 UTC
## Subject of the issue
Horizontal resizing extends on the oppsite side. Resizing a widget to the left extends its size to the right, and vice versa.

## Your environment
Issue only happens from 4.0.1 upwards. 3.3.0 works fine!
Raspberry Pi OS, Electron/Chromium

## Steps to reproduce
Video actual behaviour (bug from 4.0.1 onwards): https://streamable.com/kxykf4
Video expected behaviour (3.3.0 and below): https://streamable.com/v1y2pa

Find the code here: https://gist.github.com/riccardolardi/1a73c93d11b6486c26438fb77b9ed5d4

## Expected behavior
Resizing to the left should extend the widget size to the left.

## Actual behavior
Resizing to the left does extend the widget size to the right and vice versa. Vertical resizing (only South tested) works fine.

Thanks for your support.

**Comment by adumesny** [comment] 2021-04-16 15:24
do you see the same issue with https://gridstackjs.com/demo/mobile.html ?
if not then something in your app maybe.

or even https://gridstackjs.com/demo/float.html ? (modify to use jq version if that is what you use since you are on touch).

I can't debug your app, so you need to reproduce in a simple JS app.

**Comment by riccardolardi** [comment] 2021-04-16 15:46
Thanks @adumesny I've just modified the float demo to use jquery and resize all handles and the same issue happens. See video: https://streamable.com/eoq6er

**Comment by adumesny** [comment] 2021-04-16 16:05
top resize is known issue #1728 which I started looking at. your issue was with horizontal which I've never seen... left side resize issue was recently fixed. Right and bottom has never been an issue unlike your app video. Is that happening with simple demos ?

**Comment by adumesny** [comment] 2021-04-18 16:36
though I was not able to reproduce your original issue, I believe I have fixed this (changed how we compute moves during resizing)

should fixed in next release. don't forget to contribute if you find lib useful!

**Closed by adumesny** 2021-04-18 16:36 UTC
Labels: status:need more info, touch / mobile

**Comment by riccardolardi** [comment] 2021-04-18 16:38
@adumesny awesome! Any ETA for the next release?

**Comment by adumesny** [comment] 2021-04-18 16:51
now :)
