### ISSUE TITLE
Resizing scrolling jumping around in demo page, doesn't size correctly

### ISSUE THREAD

**Issue by Helyan47** [gridstack/gridstack.js#1745] opened 2021-04-23 20:34 UTC
## Subject of the issue
Resizing an element in Firefox causes an infinite scroll to occur and its size cannot be modified 

## Your environment
* Demo of the webpage https://gridstackjs.com/#getStarted
* Firefox / Windows10

## Steps to reproduce
Resize an element in Firefox

## Expected behavior
Resize shouldn't cause an infinite scroll

## Actual behavior
Resize an element cause infinite scroll in Firefox

https://user-images.githubusercontent.com/54754636/115926956-fa2f3180-a483-11eb-9b61-a0f2978d98e1.mp4

**Comment by adumesny** [comment] 2021-04-23 21:28
happen on Chrome win10 as well. The bouncing around whie scrolling and not sizing correctly issue was caused by #1727 in v4.2.1
(the infinite scrolling part is a feature)

**Comment by adumesny** [comment] 2021-05-08 14:36
fixed in next release.

**Closed by adumesny** 2021-05-08 14:36 UTC
Labels: type:bug
