### ISSUE TITLE
Grid collapses on itself when returned from one column view using knockout

### ISSUE THREAD

**Issue by vendelinhnastavy** [gridstack/gridstack.js#1016] opened 2019-10-14 10:40 UTC
## Subject of the issue
The following procedure causes grid to malfunction

1. Use knockout bindings to control adding or removing widgets as shown in official sample
2. Change size of browser so one-column view is shown.
3. Resize browser to full size
4. Click delete Me

The grid repositions some widgets. Some widgets lose ability to be dragged. Somethimes widgets overlap.

## Your environment
Can be tested in official gridstack.js example [http://gridstackjs.com/demo/knockout2.html](http://gridstackjs.com/demo/knockout2.html)
I tired it with three versions of gridstack.js 0.2.7,0.3, 0.4 the bahavior is the same

## Steps to reproduce

1. Use knockout bindings to control adding or removing widgets as shown in official sample
2. Change size of browser so one-column view is shown.
3. Resize browser to full size
4. Click delete Me

## Expected behaviour
Widget is removed. Other widgets stay in place

## Actual behaviour
Widgets are repositioned and overlap.

### One-column 
![1](https://user-images.githubusercontent.com/18100223/66744952-11986200-ee7e-11e9-805a-24ba3d8de835.PNG)

### Resized to full width
![2](https://user-images.githubusercontent.com/18100223/66744963-15c47f80-ee7e-11e9-8acc-063c896d3d7c.PNG)

### Removed widget
![3](https://user-images.githubusercontent.com/18100223/66744967-18bf7000-ee7e-11e9-8ebe-679dce745a6e.PNG)

**Comment by radiolips** [comment] 2019-11-05 18:45
Closing–duplicate of #1015 . Use that to track updates, please! Thanks for submitting.

**Closed by radiolips** 2019-11-05 18:45 UTC
