### ISSUE TITLE
Nested grids move outside

### ISSUE THREAD

**Issue by trevisanweb** [gridstack/gridstack.js#695] opened 2017-06-19 13:36 UTC
Hi, I'm trying to make a nested match with two grids:

![screenshot 1](https://user-images.githubusercontent.com/3501138/27287362-b93e1932-54d9-11e7-818a-c51d777ab56b.png)

I noticed that the `.grid-stack-item` class does not let it be moved out of the box, any idea how to do this?

Ex: https://codepen.io/trevisanweb/pen/JJWNVY

Thank you!

**Comment by trevisanweb** [comment] 2017-06-20 20:29
I found a solution in the file gridstack.jQueryUI.js change code line 69 `containment: this.grid.opts.isNested ? this.grid.container.parent() : null,`  -> `containment: this.grid.opts.isNested && !this.grid.opts.outside ? this.grid.container.parent() : null,` and add option plugin `.gridstack({ outside: true})`

**Comment by radiolips** [comment] 2018-05-12 14:50
Duplicate of #386.

**Closed by radiolips** 2018-05-12 14:50 UTC

**Comment by adumesny** [comment] 2019-12-22 01:39
thank you @trevisanweb  for supplying this code! this lib would not be possible without community help. fix is in next release...
