### ISSUE TITLE
Nested Grids with float don't automatically add rows on drag

### ISSUE THREAD

**Issue by bpwalker** [gridstack/gridstack.js#478] opened 2016-07-15 22:16 UTC
It seems that currently nested grids do not respect the float property fully. I am able to resize widgets like normal, but I am unable to drag them past the lowest row on the grid, where normally additional rows would be added. This seems to be due to the containment option being set to parent if the grid is nested (https://github.com/troolee/gridstack.js/blob/master/dist/gridstack.js#L1111) but the nested option this.opts.isNested , is always overrode by isNested (https://github.com/troolee/gridstack.js/blob/master/dist/gridstack.js#L557).

I don't know if this is the intended default usecase for nested float grids, but I think either line 557 should not override the user options, or there should be more control over the containment draggable option for nested grids.

**Comment by joemorcullo8** [comment] 2017-11-13 11:04
Hi, just a clarification, what's the final answer in this issue? does the nested grid will add rows on drag or not?

**Comment by joemorcullo8** [comment] 2017-11-13 13:07
Hi, where are we on this issue? I'm also having a problem for the floats of nested grids especially for the last row.

**Comment by mxx-lxg** [comment] 2018-03-14 09:10
Having the same issue. Is there a workaround for this?

**Comment by radiolips** [comment] 2018-05-12 22:02
Duplicate of #219

**Closed by radiolips** 2018-05-12 22:02 UTC
Labels: severity:normal
