### ISSUE TITLE
Locked widgets cannot be moved by the user

### ISSUE THREAD

**Issue by ztessema** [gridstack/gridstack.js#1767] opened 2021-05-27 16:00 UTC
## Subject of the issue
Locked widget cannot be moved by the user

## Your environment
gridstack.js v4.2.3, HTML5
Chrome, Windows 10

## Steps to reproduce
Widget is locked by using the 'locked' property on the gridstackNode:
`widget.gridstackNode.locked = true;`

## Expected behavior
The widget shouldn't be able to be moved due to another widgets being dragged or resized. 
The widget can still be dragged or resized by the user.

## Actual behavior
The widget shouldn't be able to be moved due to another widgets being dragged or resized. 
The widget **_cannot_** still be dragged or resized by the user.

**Comment by adumesny** [comment] 2021-05-27 16:22
first of all you should not set locked property directly (internal) but make the api call `update(widget, {locked:true})` as there is more to it than setting the flag.

second, locked = noMove (user) + noSize  (user) + can't be moved by collision constrain by another widget by design. that is the expected behavior.

**Comment by ztessema** [comment] 2021-05-27 16:37
Thank you for the information. I will use the update function. However I am still confused on the expected behavior of a 'locked' widget. According to the API:

> locked - means another widget wouldn't be able to move it during dragging or resizing. The widget can still be dragged or resized by the user. You need to add noResize and noMove attributes to completely lock the widget.
(https://github.com/gridstack/gridstack.js/tree/master/doc#item-options)

so shouldnt a locked widget be able to be moved/resized by the user?

**Comment by ztessema** [comment] 2021-05-27 16:43
More generally, how would I acheieve the behaviour of preventing the widget from being moved only by the move/resize of other widgets?

**Comment by adumesny** [comment] 2021-05-27 17:11
doc is incorrect. I'll fix that. you can't (nor have I ever seen that) widget that won't be moved by other widgets but can be moved by the user.

**Comment by adumesny** [comment] 2021-05-27 17:45
I stand corrected. in v0.5 (the furthers I went back that I worked on) `locked` can still be dragged by the user.

not sure what the use case is for... weird that items will not get pushed out but user can still manually do it.

**Comment by adumesny** [comment] 2021-05-29 14:31
fixed in next release. if you find this li useful, don't forget to donate!

**Closed** 2021-05-29 14:31 UTC
Labels: type:bug
