### ISSUE TITLE
Firefox: [3.3.0] Widget outline not rendering under cursor when dragging new widget on grid

### ISSUE THREAD

**Issue by Mopster** [gridstack/gridstack.js#1626] opened 2021-02-19 03:26 UTC
## Subject of the issue

I'm experiencing issues with the drag&drop since 3.3.0, 3.2.0 had no issues. 

When dragging a widget, the outline renders at the bottom of the grid instead of below the cursor. 

![gridstack-3 3 0](https://user-images.githubusercontent.com/155956/108453228-72734e00-72ad-11eb-9d36-91a144c2a286.png)

When dropping the widget :

![Screenshot from 2021-02-19 12-23-00](https://user-images.githubusercontent.com/155956/108453244-7acb8900-72ad-11eb-9d30-d3f43f870aa4.png)

## Your environment

* v3.3.0 using HTML5
* FireFox 85.0.1 (on Ubuntu 20.04)

## Steps to reproduce

The outline render issue can be reproduced on https://gridstackjs.com/demo/advance.html 

Delete all existing widgets and then drag a new widget around the grid.

## Expected behavior

The widget outline in the grid would be rendered under the cursor.

## Actual behavior

The widget outline is not rendered below the cursor and seems to prefer the bottom of the grid

**Comment by adumesny** [comment] 2021-02-21 02:28
@Mopster are you running against 3.3.0-dev (latest tree) as I can see issue but 3.3 and 3.2 official seem fine.

**Comment by Mopster** [comment] 2021-02-21 03:19
@adumesny no, not running dev, using the 3.3.0 release.
"shasum": "e324de1acbe59b812293117783c398ca83e2d1ca"

I'm experiencing the issue on the demo pages on gridstackjs.com

I just tested using Edge ( 88.0.705.74) on Windows 10 and also experiencing issues on https://gridstackjs.com/demo/advance.html
This time, the widget outline sticks to the top of the grid and I can't place widgets on any row except on a row that has an existing widget or below. So if there's a widget on row 1, I can only place a widget on row 1 and 2.

Steps to reproduce : 
1. Clear grid of all removable widgets
2. Place a couple of widgets

**Comment by adumesny** [comment] 2021-02-27 23:00
| (edge win10) This time, the widget outline sticks to the top of the grid and I can't place widgets on any row

that is the correct behavior - with `float:false` (default) things have top gravity.

I tried FF win10 (and edge, and Chrome) and it all works fine, so please post a video and I'm not able to reproduce (will be a  lot for work for me to test on Ubuntu). Closing until you do. thanks

https://user-images.githubusercontent.com/3496166/109402675-7ab23580-790c-11eb-8f9f-0fc9a7cb910f.mp4

**Comment by Mopster** [comment] 2021-03-02 06:47
This is a video from FireFox on Ubuntu, I'll check later if I can create one on Windows

https://user-images.githubusercontent.com/155956/109609250-6c635400-7b6e-11eb-8157-50a81bb236f4.mp4

**Comment by adumesny** [comment] 2021-03-02 14:58
wondering if you are moving things too fast which would be a dup of  #1578 - does it happen if you drag them SLOW ?
trying to narrow the  issue...

**Comment by Mopster** [comment] 2021-03-03 08:18
Dragging them slowly did not change the behavior, it's the same as shown in the video above.

I did some additional testing and it seems to be an issue on Firefox only for me now.
* Ubuntu - Firefox : issue
* Ubuntu - Chrome : no issue
* Win10 - Edge : no issue
* Win10 - Firefox : issue
* Win10 - Chrome : no issue

**Comment by adumesny** [comment] 2021-03-03 16:57
I see the issue now on FF win10. thanks.

**Comment by adumesny** [comment] 2021-04-11 14:32
closing issue as it's working fine in 4.1.0-dev (latest)

**Closed by adumesny** 2021-04-11 14:32 UTC
Labels: type:bug

**Comment by Mopster** [comment] 2021-04-14 02:49
Looks like it's working! Thanks!
