### ISSUE TITLE
Widget over another widget

### ISSUE THREAD

**Issue by toschispaggiari** [gridstack/gridstack.js#2719] opened 2024-06-26 08:46 UTC
## Subject of the issue
Creating or moving widgets, sometimes it happens that a widget goes over another.

## Your environment
gridstack 10.2.1
windows 11 + chrome 126/firefox 127

## Steps to reproduce
I'm trying on my local website using vue and the latest version of gridtack (10.2.1), but I also tried on official website.
The behavior happens randomly just dragging widgets.
I attach a screenshot and a video trying on official website. 

![Screenshot 2024-06-26 102338](https://github.com/gridstack/gridstack.js/assets/106581048/54681e22-4532-4c94-9059-b674256bd256)

https://github.com/gridstack/gridstack.js/assets/106581048/46d654d1-b2b4-4a05-897a-13a240eba481

## Expected behavior
I think a widget could not go over another widget.

**Comment by adumesny** [comment] 2024-06-26 13:47
I'm not able to reproduce this (and can't play your video for some reason). did this happen at a specific release ? can you provide exact steps to reproduce ?

**Comment by toschispaggiari** [comment] 2024-06-26 14:00
We tried with release 10.1.2 and then we updated to 10.2.1 but the behavior is the same.
Sometimes, when you drag a widget, it can be placed over another widget. 
I try to attach the video again.


https://github.com/gridstack/gridstack.js/assets/106581048/470fb023-8e2c-4e5b-adb5-98293273b308

**Comment by adumesny** [comment] 2024-06-26 21:08
there is a locked item in there, so maybe that's triggering more complex cases ? have you seen it without a locked item ?

**Comment by toschispaggiari** [comment] 2024-06-27 06:47
I had the issue in my local website, with customized style widgets.
I can attach a screenshot, where you can see 2 widgets over another. 
It happens randomly, I cannot reproduce the behavior everytime.

Here the settings I used to init gridstack:

```
grid = GridStack.init({ 
    float                   : false,
    minRow                  : 1,
    resizable               : {
        handles : 'e, se, s, sw, w'
    },
    removeTimeout           : 100,
    animate                 : true,
    cellHeight              : '120px',
    column                  : 6
});
```

![Screenshot 2024-06-26 102822](https://github.com/gridstack/gridstack.js/assets/106581048/02ff005f-8cf2-4bfb-8b94-6061fc004977)

**Comment by adumesny** [comment] 2024-07-21 15:44
it would be useful if you pinpoint when this actually started happening then I can see what set of code changes went it... assuming this is new (regression) sicne I've never heard of this before.

**Comment by adumesny** [comment] 2024-09-08 15:44
closing as I'm unable to reproduce locally.

**Closed by adumesny** 2024-09-08 15:44 UTC
Labels: status:need more info
