### ISSUE TITLE
Incorrect order of items if a height of one item has been changed manually

### ISSUE THREAD

**Issue by ruslauz** [gridstack/gridstack.js#2206] opened 2023-02-04 20:24 UTC
## Subject of the issue
In case if you are changing a height of one item by changing the `h` property for instance by changing a state in react app you can face an incorrect order of items, i.e. the item standing next to the changed item is moved to the end of the list.

![screencast 2023-02-04 21-57-02](https://user-images.githubusercontent.com/59659358/216787688-29a38607-22eb-4958-974f-feb8b0e71c12.gif)

## Your environment
* version of gridstack.js - 7.2.3
* OS - MacOs  13.0
* Browser - Chrome Version 108.0.5359.98 (Official Build) (arm64)

I managed to fix it locally by changing the third parameter of the `_fixCollisions` method on the 671 line of the `gridstack-engine.ts` file from `collide` to `undefined` forcing it to define collisions once again and to start moving items from the last to the first in the list

<img width="853" alt="gridstack-engine ts — Frontend 2023-02-04 22-14-13" src="https://user-images.githubusercontent.com/59659358/216788156-fd441787-4fd9-47f4-9593-d75e98a58dea.png">

![fixed](https://user-images.githubusercontent.com/59659358/216788472-1a41ea1a-8d7c-4fd8-a08f-4171ec0aa502.gif)

I can send a PR if it is a bug and not the feature

**Comment by adumesny** [comment] 2023-02-05 00:50
hey thanks for filling it and fixing it ! let me reproduce it locally and see your fix, because we do want to re-use the collision node , but maybe not for the next nested level down...

**Comment by ruslauz** [comment] 2023-02-05 17:41
Hey,  Alain. My solution looks like a hack. When i was debugging the problem i found out that the list of collisions is fixed from the last item to the first, but in the line `658` of the `gridstack-engine.ts` we take the first one and then pass it to the `_fixCollisions` method. 

<img width="907" alt="gridstack-engine-1" src="https://user-images.githubusercontent.com/59659358/216835186-1f427b3f-2e74-4172-a2ca-a951e4e5318a.png">

First of all I tried to change this line to take the last item in the list of collisions.

<img width="1070" alt="gridstack-engine-2" src="https://user-images.githubusercontent.com/59659358/216835220-e9bf085a-4095-4a07-9810-70dc5e6c646b.png">

Logically this approach should have fixed the problem but due to some unknown logic (i have not debugged) it fixed only the position of the first item and as far as i remember it broke the position of the last. Therefore i decided to change the `collision` parameter to `undefined` and that worked for me.

I am sure almost on 100% that there is an another way to fix the problem but it was a quick fix. And you are as a maintainer know better what should have done. By the way the working example from the screenshots above can be found  in that [commit](https://github.com/gridstack/gridstack.js/pull/2207/commits/dd868975ff9bb9f57f4efc94c84f3b26637971e5#diff-18a68a0f2b517ae47242fe6a034149f9d96f0468518655b52f8a494df0e5fcbf)

**Comment by adumesny** [comment] 2023-02-05 19:13
can you post a jsfiddle (or similar) TS example like https://jsfiddle.net/adumesny/jqhkry7g showing the issue (as bug request mention) **without React** ? then I can add it to the automated tests...

If it works by user resizing but not by `update()` then we need to make update behave the same (maybe misisng the active item being 'dragged') as loosing the collision and not re-using is not an optimization I want to loose.

**Comment by ruslauz** [comment] 2023-02-05 19:53
Please let me know if it is good example - https://jsfiddle.net/sergeifomin/36gjz58o/57/

**Comment by ruslauz** [comment] 2023-02-05 21:22
> 

Will this type of fix save necessary optimizations?

<img width="893" alt="gridstack-engine-3" src="https://user-images.githubusercontent.com/59659358/216846780-ee60b530-3e57-45cd-9a17-2732c18fe22a.png">

**Comment by adumesny** [comment] 2023-02-10 22:04
FYI,calling update on that one widget instead of reloading entire grid, which is a better way anyway, works.
still a bug, but lower priority...
https://jsfiddle.net/adumesny/jau5s473/

**Comment by ruslauz** [comment] 2023-02-10 22:13
Thank you! The quick question - if we add an additional check before call of update method in the load method will we achieve the same as wee skip nodes which do not need any update and also get an additional optimization?

For instance like this
<img  alt="image" src="https://user-images.githubusercontent.com/59659358/218208517-4d41b47f-c8e5-492d-8ad8-ff1c49b10562.png">

**Comment by ruslauz** [comment] 2023-02-10 22:17
Yes you are right, the function like shallowEqual would help

**Comment by adumesny** [comment] 2023-02-11 01:53
fixed in next release. don't forget to donate if you find this lib useful!

**Closed by adumesny** 2023-02-11 01:53 UTC
Labels: type:bug, severity:low
