### ISSUE TITLE
save(true) and save(false) both appear to create JSON that contains the content

### ISSUE THREAD

**Issue by cfcoder** [gridstack/gridstack.js#1795] opened 2021-06-24 01:24 UTC
## Subject of the issue
Both the save(true) and save(false) output the same JSON data. Both have html content.

## Your environment
* version of gridstack.js gridstack@4.2.5 using HTML5 version
* which browser/OS Brave Version 1.25.73 Chromium: 91.0.4472.106 (Official Build) (64-bit)

## Steps to reproduce
https://jsfiddle.net/ve0sdunm/3/

1. Run jsfiddle

## Expected behavior
First two console outputs should show html content in the JSON, 3rd should not include content in the JSON

## Actual behavior
All 3 JSON outputs look the same and include the content.

**Comment by adumesny** [comment] 2021-07-03 03:21
save(true) is not about your node .content field (which is always left alone if present) but the DOM element itself... which I recall doing to subclasses could parse after and add additional info they needed, but I think a callback per item would be better than save the dom element.

**Comment by adumesny** [comment] 2021-07-11 14:28
not a bug per say, but missing documentation.... the .content you specify doesn't get deleted when calling save(false) (not sure it should - let me know if you feel strongly about that) but save(true) loading the latest content instead.

**Comment by adumesny** [comment] 2021-07-11 16:00
fixed in next release. don't forget to contribute if you find lib useful!

**Closed** 2021-07-11 15:59 UTC
