### ISSUE TITLE
FF: Disappearing items when dragging fast between 2 grids

### ISSUE THREAD

**Issue by drzraf** [gridstack/gridstack.js#1733] opened 2021-04-17 03:11 UTC
## Subject of the issue

HTML 5 drag & drop across two grids frequently results in items being lost. 

## Your environment
* Gridstack.js 4.2.0 + HTML5 D&D
* On Firefox

## Steps to reproduce
https://jsfiddle.net/fc8n3wmj/

## Expected behavior
Drag some items back and forth between both grids.

## Actual behavior
After a couple of attempt 5 or 10, the item will disappear.
It's still part of `GridStack.engine.nodes` but not part of `GridStack.getGridItems()` anymore (probably because the DOM node was either removed or somehow _hidden_).

## Note

- When this happen logging shows that the last known GS event is a `dragstop` (The destination grid never receives any `added` event)
- I wondered whether the destination could simply not be _ready_ to receive the element (timing issue)?
- Under some circumstance, with the above jsfiddle, I also encountered situation were the items would be kind of _"locked"_. It's probably unrelated but still strange since no code would do that.

**Comment by adumesny** [comment] 2021-04-17 16:03
thanks for submitting this - does it happen with other browsers (Win 10 Chrome seemed fine to me) and what platform.

Also can you reduce the example down to much simpler example ?

**Comment by drzraf** [comment] 2021-04-18 00:23
You're right. I'm **unable to reproduce** the disappearance symptom (nor the _locked grid_ one) on **Chrome** (on Linux), while I observe a small "freeze effect" when I start dragging items.

(On Firefox, there is no such "freeze effect" but the problems are very easy to reproduce)
I'm sorry it's hard to really strip down even more right now (but I also tend to think it's Firefox-only problem possibly not fixable as GS level).
Still, if you get a chance to try Firefox on Win 10, I'm interested to know whether it's affected.

**Comment by adumesny** [comment] 2021-04-18 04:10
not seeing on FF win10. please post a video and reduce down to simple code or I can't take a look.

**Comment by drzraf** [comment] 2021-04-19 15:23
Reproducer https://jsfiddle.net/1m5spd3x/

https://user-images.githubusercontent.com/1169926/115261510-0fb1fd80-a10a-11eb-88a3-8c0212172e8c.mp4

**Comment by adumesny** [comment] 2021-04-19 15:36
link above is wrong and looks like original example with stuff like this which has nothing to do with gridstack lib
```js
 var cnf = [
	  {
	      "key": "firstname",
	      "x": 0,
	      "y": 0,
	      "width": 1,
	      "height": 1
	  }
```

**Comment by drzraf** [comment] 2021-04-19 18:35
Ouch, sorry, I forgot to _save_ the new JSfiddle with simplified code.
Now it's at https://jsfiddle.net/5g7Loe01/ (and edited my previous post).

The "cnf" part was part of the original example and was stripped down in the simplified reproducer.

**Comment by adumesny** [comment] 2021-04-20 15:18
thanks for the trimmed down example. I was going to say I still can't reproduce on FF win10, but the second time I recorded it (I was going to show how it works fine) I was able to briefly see the issue - see the end of the video - so might be able to fix this and likely related to #1578 #1647 which I thought I did address in #1652

does this happen if you move items slowly or only when fast ?

also your example shows 2 other issues
1) you set a CSS min height for the right side grid, but that is overwritten once you drop in item in there. might want to set `minRow:8` similar to the other or something. Post separate bug
2) resizing items on the right grid is broken. scrollbar issue (maybe fixed in 4.2.1 ?) or being 2 column, or....

also your code can be cleaned up further. I'll post an update

https://user-images.githubusercontent.com/3496166/115421612-f44dfd80-a1b0-11eb-86c6-953fb184db3b.mp4

**Comment by drzraf** [comment] 2021-04-21 03:24
For me it's much more easy to reproduce. If I'm particularly slow and ensure I see the dashed-placeholder, it always works.
But at a normal pace, it happens consistently after one or two d&d. It seems that the dashed-placeholder way too slow to show up and if it's not visible, the item is certain to disappear.


I'm not sure about the two other problems you're mentioning. But as said before, one problem I also encountered with my jsfiddle (but not yours) is that items (on the left side) get "stuck" (not draggable/movable anymore).

NB: I don't know how I could have missed to two already reported bugs

**Comment by adumesny** [comment] 2021-04-21 14:14
well the 2 bugs were closed as I was able to track and fix those issues, but since I can't easily reproduce yours it's going to be hard to fix.

it might be best for me to give you debug build with event tracking so you can send me the logs for me to see what's happening... if you can do that and get on slack we can try to fix this FF/Linux issue (for me to setup a virtual machine to debug it will be a pain).

**Comment by drzraf** [comment] 2021-04-21 16:34
> it might be best for me to give you debug build with event tracking so you can send me the logs for me to see what's happening... 

Sure thing.

**Comment by bcbuddy** [comment] 2021-04-29 17:01
I can confirm I have experienced the same issue since upgrading to version 4.2 from 2.X

I think it has something to do with removeTimeout being removed from the options. I used to set that to a smaller value to bypass this issue, now the issue has come back.

**Comment by adumesny** [comment] 2021-04-29 19:39
@bcbuddy is it browser specific and what OS ? I believe the `removeTimeout ` was only used when dragging to trash can (remove) not between grids, and didn't see the point, but will have to take a look.

**Comment by bcbuddy** [comment] 2021-04-29 23:02
Oh maybe it wasn't removeTimeout then, that's odd... it does still happen to me and I have only tested in Chrome so far.  Windows 10

**Comment by adumesny** [comment] 2022-09-17 23:39
closing as I re-wrote dragging in v6 and bet this is fixed now,

**Closed by adumesny** 2022-09-17 23:39 UTC
Labels: type:bug
