### ISSUE TITLE
knockout Deleting widget issue (related with browser's resizing)

### ISSUE THREAD

**Issue by ggenute** [gridstack/gridstack.js#1015] opened 2019-10-11 21:56 UTC
## Subject of the issue
Deleting widget issue (related with browser's reducing to display widgets in one column)

## Your environment
* version of gridstack.js 1.0.0-dev
* Google Chrome Version 77.0.3865.90

## Steps to reproduce
http://gridstackjs.com/demo/knockout.html http://gridstackjs.com/demo/knockout2.html
1. Resize the browser **from displaying few gridstack columns to one column**. Don't refresh the page.
2. Try to delete 3rd widget from the top, it deletes 1, 2, 3 widgets and doesn't removes 1st and 2nd widgets from the DOM.
3. Without page refresh come back to the full screen browser, the display of widgets is broken.

## Expected behaviour
Deleting should work when the browser is resized from displaying few gridstack columns to one column.

## Actual behaviour
When the browser is resized / reduced **from displaying few gridstack columns to one column**, deleting widgets doesn't work. After coming back to the full screen browser, the display of widgets is broken.
![Picture_1](https://user-images.githubusercontent.com/36604140/66687276-c7c63680-ec47-11e9-9a9f-5a5dd9c98f82.JPG)
![Picture_2](https://user-images.githubusercontent.com/36604140/66687277-c7c63680-ec47-11e9-9c09-682426e4029c.jpg)
![Picture_3](https://user-images.githubusercontent.com/36604140/66687274-c7c63680-ec47-11e9-8eda-76868f2647d2.jpg)

**Comment by radiolips** [comment] 2019-11-11 21:12
Hey @ggenute . I was able to replicate the problem. When the original examples were written, they didn't take into account single-column-mode. I'll fix the demos when I have time, but for the time being, the issue is that when it attempts to remove the widget with `self.widgets.remove(item);`, it's comparing and `item`, which has single-column attributes, to an array of widgets with original specs.

**Comment by adumesny** [comment] 2019-12-21 02:09
@ggenute are you running into this as a knockout  app, or just found this in our demo ?

**Comment by ggenute** [comment] 2019-12-21 02:13
@adumesny first I noticed at my app, and double checked how it works your demo. The same issue is in both.

**Comment by adumesny** [comment] 2020-02-17 03:41
@ggenute this is fixed in current release. I completely re-wrote `oneColumn` mode (just `setColumn(1)` now so demos don't show any issues anymore.

Let me know if it doesn't work for you!

**Closed by adumesny** 2020-02-17 03:41 UTC

**Comment by ggenute** [comment] 2020-02-17 19:04
Hey @adumesny. Updated to latest release. It works on my project as well. Thanks!
