### ISSUE TITLE
could support nest grid more than 2 level

### ISSUE THREAD

**Issue by joebnb** [gridstack/gridstack.js#1943] opened 2022-03-28 08:55 UTC
https://github.com/gridstack/gridstack.js/blob/afd7349ec4a0c54847d31703123efd1d037f2548/src/gridstack-dd.ts#L135

if remove this line it's seems almost finish about mutiple level,could implement this.

**Comment by joebnb** [comment] 2022-03-28 09:01
![2022-03-28 16-57-48 2022-03-28 16_59_00](https://user-images.githubusercontent.com/1646883/160363552-31ed3d4f-2b9c-45d3-9c1e-9ae1a2c445bc.gif)
if comment this line, it will looks like this image,there are 2 problem to use this

incorrect grid width and height and if drop disappear  in some case when the drop shadow not show

**Comment by v1talii-dev** [comment] 2022-06-06 15:40
are there any updates on this issue? perhaps you managed to find a workaround?

**Comment by v1talii-dev** [comment] 2022-06-10 15:20
As far as I was able to identify, the problem is that style classes are not applied to elements in the subgrid.

this is how it looks before the changes:
![image](https://user-images.githubusercontent.com/12966923/173095859-254a5bc7-8c04-4d66-ab63-17183fc9fd68.png)

and so after dragging:
![image](https://user-images.githubusercontent.com/12966923/173096100-b8f43c84-be91-4e9c-a8ad-f48995d85ede.png)

but if you immediately render the fields, then it is output correctly:
![image](https://user-images.githubusercontent.com/12966923/173097530-3509d6bc-5621-45d4-a168-48cfa47a3631.png)

however, after that, if you drag the tabs, there will be the same incorrect behavior...

**Comment by adumesny** [comment] 2022-06-14 20:56
thanks, but as I mentioned dragging to created new nested grids is a big feature request...

**Comment by v1talii-dev** [comment] 2022-06-15 10:23
I found a workaround, it seems to work. @adumesny please see the [PR](https://github.com/gridstack/gridstack.js/pull/1980).

**Comment by adumesny** [comment] 2022-09-26 14:33
fixed by #2052 for general drag to create sub-grids feature in v7

**Closed by adumesny** 2022-09-26 14:33 UTC
Labels: type:enhancement, status:need more info
