### ISSUE TITLE
Resizing Widgets not working well

### ISSUE THREAD

**Issue by can0199** [gridstack/gridstack.js#1470] opened 2020-11-18 17:29 UTC
## Subject of the issue
Hey first of all thanks for the very nice libary, i dont know if its a bug of the libary or a misconfiguration on my side.
I have trouble with making the gridstack responsive, if i first view the grid in desktop view and then switch to mobile everything looks very smooth and nice on the mobile view but if i directly load the mobile view the gridstack elements have very low height and looks very broken.

desktop view:
![desktop-start](https://user-images.githubusercontent.com/60479637/99565323-c7ac7480-29cb-11eb-88d4-af4d794c2007.png)

mobile view but first i loaded the site on desktop view then i changed to mobile view over chrome dev tools, the widgets looks very nice for me
![desktop-to-mobile](https://user-images.githubusercontent.com/60479637/99565349-cd09bf00-29cb-11eb-86fd-97830bc03850.png)

this is the mobile view if i am not switch from desktop to mobile:
![mobile-start](https://user-images.githubusercontent.com/60479637/99565144-9b90f380-29cb-11eb-8d9b-f8d6b239397b.png)

Do you have any ideas why this is happening?

## Your environment
* 2.2.0
* Chrome 86

## Steps to reproduce
I initialize the grid with following options:
```
    let $gridStackSettings =  {
      float: true,
      staticGrid: true,
    };
```
Function i use to resize the grid

```
GridStack.prototype.resizeGrid = function (width) {
  let column;

  if (width < 700) {
    column = 1;
  } else if (width < 850) {
    column = 3;
  } else if (width < 950) {
    column = 6;
  } else if (width < 1100) {
    column = 8;
  } else {
    column = 12;
  }

  this.column(column);
};
```
I call the function once after initializing the grid  and  with a event listener on window.resize
`$gridstack.resizeGrid(document.body.clientWidth);`

**Comment by adumesny** [comment] 2020-11-18 19:47
$ everywhere... must be a jquery guy :)   (I removed JQ from gridstack API in 1.x). You don't really need 'patch' gridstack with your method (in case I use that name in the future), you should follow the responsive.html example instead.

Anyway, to answer your Q - cell heights if not specified will automatically be computed to make a cell square (so width / # columns). you can add `cellHeight: 70px` in grid options to force it to a value.

My guess is when loading directly to mobile (you don't specify how) it has a much smaller screen BUT hasn't switched to 1 columnMode yet and does ~700px/12. hard to tell without a reproduceable case.
Please post a running sample showing the bug (I supply a jsfiddle example) so we can have a look. Closing until you do so...

And don't forget to contribute if you can.

**Closed by adumesny** 2020-11-18 19:47 UTC

**Comment by can0199** [comment] 2020-11-18 22:18
Thank you for your fast response, i learnded javascript first with jquery but now i am try to avoid it :D
I made a fiddle of the problem:
[JSFiddle](https://jsfiddle.net/szphx8uc/)
i took the basic code from your responsive demo i modified the demo code a little bit, because jsfiddle and chrome crashed without the changes. I wrapped the function of the resize event handler with a debounce function.

Too understand what my problem is, please run the fiddle first with a window size where the column is set to 12 then resize the window until the column is set to 1 after this please run the fiddle again(column has to be 1) and resize the window until the column is set to 12. I think then you understand better what i mean

Thanks in advanced

**Comment by adumesny** [comment] 2020-11-18 23:14
you are doing this 
```js
grid = GridStack.init({float: true, staticGrid: true}});
grid.load(items);
resizeGrid();
```
so you ALWAYS starting with 12 column, which means cellHeight is window-width/12 since you specify it (hence very skinny on phone), THEN doing a size down to N columns. If you want square tiles 1x1 you need to set the `column: X` as well and change class type (see doc), OR manually set `cellHeight: somevalue` (simpler) when you init the grid.

not a bug in lib.

**Comment by can0199** [comment] 2020-11-19 13:44
ahh okay thank you for you help :)

**Comment by adumesny** [comment] 2020-11-20 15:43
part of what you mention (loading to size column 1, then going up to 12) is same as #1471 , but the other part about having skinny 1 column cellHeight has to do in how you init the grid which I assume is doing  12 column to calculate the init cellHeight. Make sure to use `disableOneColumnMode: true` if you're gonna control the column yourself, or make sure `minWidth` matches your 1 column mode (768px by default)
