### ISSUE TITLE
Resizing item height produces item taller than expected on first item added to grid only

### ISSUE THREAD

**Issue by wx007** [gridstack/gridstack.js#573] opened 2016-12-21 03:10 UTC
I noticed an anomaly while resizing the first item added to a grid. 
You should be able to replicate it by editing the Serialization demo so that the serializedData array contains only the first item. 

The anomaly is that when you resize the item’s height the placeholder's vertical position (the gray outline) seems to accumulate some sort of math error. The result is that once you stop resizing at the 8th square down, for example, the item will suddenly “jump fill” to the 10th square. The jump is larger the taller you resize the item.
After investigating a bit I noticed this jump only occurs on the first item added to the grid and cellHeight seems to change dramatically between the first and successive items. Note that the width seems fine.

gif attached:
![kapture 2016-12-20 at 18 56 31](https://cloud.githubusercontent.com/assets/4182007/21376016/b13d5850-c6ff-11e6-8fde-715fdd318b26.gif)

**Comment by radiolips** [comment] 2016-12-27 01:10
@wx007 Interesting. This is only happening if the `grid` has a single item?

**Comment by radiolips** [comment] 2016-12-27 01:12
This doesn't appear to be happening in my personal use of `gridstack`. Could you prepare a jsfiddle for me to see this in action? Thanks!

**Comment by wx007** [comment] 2017-01-20 16:16
Sorry for the delay. Here you go:  https://jsfiddle.net/5ux1y3dr/

This code is taken directly from the GitHub repository (serialization.html demo). The only change I made was to remove all but the first item from the serializedData array.

Note you'll either need a large computer monitor or have to shrink everything in order to fully see what's going on. You'll see the effects as the yellow background area increases at a cumulative rate. I would think it should never be taller than the height of a single grid item.

**Comment by radiolips** [comment] 2017-04-22 15:47
@wx007 Huh, that's weird. I was able to reproduce the problem. I'll give you an update when I have one.

**Comment by idxEAGLE** [comment] 2017-08-18 22:40
I am not sure, if it is important and actual, I faced with similar issue today and found out that in my case it is not depend on single the element in grid or not. In my case when height size > 1 then size of element is:
elemenHeight = cellHeight * cellSize + (cellSize - 1) * verticalMargin. So, if verticalMargin in options is set as 0 - the issue is resolved for the result size of widget. So, I think that verticalMargin is root of case...

**Comment by akiross** [comment] 2018-02-15 17:42
This also happens to me. It happens with many elements as well, not just one.

I think what is happening is that height of the parent item is larger than the height of the area your mouse is moving into (the screen). When I start dragging the handle to resize, **if** the height of the parent is larger than the screen (i.e. overflows), then I get errors in the computed grid heights. If the parent height is less than screen height, then there are no issues.

I attach below an animation showing the behaviour on my browser (Firefox 58). As you can see, it seems that the height of the "target" is computed starting from the height of the parent: if the parent is too big (that is, bigger than the viewport), then things will degenerate and targets will overflow.

![bug_animation](https://user-images.githubusercontent.com/884092/36271661-8ea5422c-127f-11e8-8172-ce99a4f23c7e.gif)

**Comment by radiolips** [comment] 2018-05-10 20:00
I believe this is resolved in the dev branch. I'm unable to recreate it. I'm closing this issue, but if someone is still having this issue and can provide a codepen for me, I'd be happy to take another look.

**Closed by radiolips** 2018-05-10 20:00 UTC
Labels: severity:minor, type:bug
