### ISSUE TITLE
Missing properties in serialization ?

### ISSUE THREAD

**Issue by TheAndre980** [gridstack/gridstack.js#2084] opened 2022-10-17 12:09 UTC
## Subject of the issue
In my project, i have a listener of the grid on 'change', the items returned in the function didn't change in the new version but the save function doesn't always return the width of the widget. currently im using the save function to keep track of permissions on the function 'change'
*sorry if i should have asked on slack but didn't know how.

## Your environment
gridstack v7.0.0

## Expected behavior
v6.0.0 - v6.0.3
![v6](https://user-images.githubusercontent.com/12530025/196172396-6e9753c7-8241-4453-b8be-0958cf9b18fd.PNG)

## Actual behavior
with extra log for the items returned in the function, then it shows the console log of the save function
![v7](https://user-images.githubusercontent.com/12530025/196172434-71867641-edad-402e-84a3-73072c039af4.PNG)

**Comment by adumesny** [comment] 2022-10-22 19:24
first off you need to provide a running example for me to debug...

Are you saying that w=1, h=1 are not being sent out when saving ? that is by design now since they are default values (just like all the other fields not being set or false). reduces noise/storage need.

closing until I hear otherwise...

**Closed by adumesny** 2022-10-22 19:24 UTC
