### ISSUE TITLE
Losing event-handlers after .save and .load in React

### ISSUE THREAD

**Issue by malininss** [gridstack/gridstack.js#2037] opened 2022-09-13 14:45 UTC
## Subject of the issue
I use React and gridstack.js. I have created several "grid-stack" blocks and I want to move widgets between these blocks (columns).

I want the grid to be sort by certain trigger (in this example, this is clicking on the button)

In the example below, I change (reverse) the position of the elements in the "grid-stack" blocks and load new data via the method .load.

When I shuffle the elements between the blocks in this way (I save via grid.save(), make changes to the grid and load it into another grid-stack block), all event handlers on the widgets stop working. In this example it is onClick.

Is there the way to prevent this behavior and don't lose event handlers on elements?
It is necessary for me to create several "grid-stack" blocks and sort them like this. 

## Your environment
* Gridstack 6.0.1
* React 16.12.0
* Google Chrome Browser

## Steps to reproduce
Code example:
```
const SomeComponent = () => {
    const refGrid = React.useRef();

    useEffect(() => {
        refGrid.current = GridStack.initAll({
            'column': 2,
            'minRow': 1,
            'cellHeight': 160,
            'disableOneColumnMode': true,
            'float': false,
            'acceptWidgets': () => true,
        });
    }, []);

    const handleGridElementClick = () => {
        console.log('Clicked');
    };
    
    const handleButtonClick = () => {
        const newGrid = refGrid.current.map((grid) => {
            const serializedData = grid.save();
            return serializedData;
        });
        
        const reversedNewGrid = newGrid.reverse();
        
        refGrid.current.forEach((oldGrid, index) => {
            oldGrid.load(reversedNewGrid[index]);
        });
    
    };

    return (
        <div>
            <Button onClick={handleButtonClick}>
                ReversElementPositions
            </Button>
            <div className="grid-stack">
                <div
                    className="grid-stack-item"
                    gs-id={"one"}
                    gs-w={2}
                    gs-h={1}
                >
                    <div
                        className="grid-stack-item-content"
                        onClick={handleGridElementClick}
                    >
                        WIDGET CONTENT 1
                    </div>
                </div>
            </div>
            <div className="grid-stack">
                <div
                    className="grid-stack-item"
                    gs-id={"two"}
                    gs-w={2}
                    gs-h={1}
                >
                    <div
                        className="grid-stack-item-content"
                        onClick={handleGridElementClick}
                    >
                        WIDGET CONTENT 2
                    </div>
                </div>
            </div>
        </div>
    );
}
```
## Expected behavior
After moving widgets between grid-stack block via the methods .save and .load event handlers are working 

## Actual behavior
When I move widgets between grid-stack blocks the event handlers stop executing

**Comment by malininss** [comment] 2022-09-14 09:51
I see that the problem is related to the situation that we removing the widget in the .load method and creating again in a different grid container via method .addWidget, that takes property "content" which is a string, without handlers and etc.

And after that React lose connection with this node. Maybe somebody has ideas how to solve this issue? It seems impossible

**Comment by adumesny** [comment] 2022-09-17 23:37
In React/Ang/Vue the framework has to create/delete the DOM, then you call makeWidget() on it to add GS features. closing as not a bug.

**Closed by adumesny** 2022-09-17 23:37 UTC
