### ISSUE TITLE
Grid is not responsive when resizing

### ISSUE THREAD

**Issue by vishakaw1** [gridstack/gridstack.js#807] opened 2017-10-24 02:58 UTC
Hi, I pulled out the latest commit from github(#786) and build a grid with 6 widgets. Following scenario shows the expected behaviour.
100%
[1,2,3]
[4,5,6]

50%
[1,2]
[4,5]
[3,6]

one column mode
[1]
[2]
[3]
[4]
[5]
[6]

But when resizing, widget order, Number of rows and positions are all wrong like following.

100%
[1,2,3]
[4,5,6]

50%
[0,2]
[3.5]
[ ,1]
[ ,4]

one column mode
[0]
[2]
[3]
[5]
[1]
[4]

Also, while maximize, the item sizes are wrong and are not arranging the same order.
**Can we expect this behaviour from your version 1.0 release.**

![responsive-gridstack-desktop-view](https://user-images.githubusercontent.com/20429310/31922804-dba4715e-b8c2-11e7-88fa-b3df4e088183.png)

![responsive-gridstack-ipadview](https://user-images.githubusercontent.com/20429310/31922807-dfdfd650-b8c2-11e7-9082-1e07f5b20c38.png)

![responsive-gridstack-iphoneview](https://user-images.githubusercontent.com/20429310/31922810-e3f2029a-b8c2-11e7-95f1-e26d576ae43b.png)

![maximizing-back-to-desktop-view](https://user-images.githubusercontent.com/20429310/31922812-e855727c-b8c2-11e7-9e4b-9be633d2d000.png)
[responsive-gridstack.zip](https://github.com/gridstack/gridstack.js/files/1409392/responsive-gridstack.zip)

**Comment by radiolips** [comment] 2018-05-12 15:18
Duplicate of #520

**Closed by radiolips** 2018-05-12 15:18 UTC
Labels: type:bug
