### ISSUE TITLE
anyone has reactjs using gristack example

### ISSUE THREAD

**Issue by eagoo** [gridstack/gridstack.js#735] opened 2017-08-08 06:16 UTC
while https://github.com/pitrho/react-gridstack is not working

**Comment by DoctaWorm** [comment] 2017-08-08 16:22
As much as I like gridstack and have been using it for about two years, if you're in a pure react environment I'd recommend looking into this one: https://github.com/STRML/react-grid-layout

**Comment by derwaldgeist** [comment] 2017-08-14 20:06
Unfortunately, react-grid-layout doesn't work well on mobile (touch) devices. Is there another alternative? I also like gridstack, but the (fixed) dependencies on jQuery and jQueryUI are a problem for me.

**Comment by radiolips** [comment] 2017-09-05 16:57
@derwaldgeist The dependencies will be removed in version 1. This has been delayed for no particularly good reason, but the dependencies _will_ be removed. The resize/dragging functionality will need to be supplemented (I've only been working with one other plugin but any plugin should work - you'll also be able to roll your own if you'd like).

@eagoo shoot. I'm sorry. I think there are a few other react tickets open, but I'll leave this open for now. If anyone (anyone!) wants to participate in getting gridstack and react working in harmony, please do so. I'd be happy to link a working example it in the readme.

**Comment by jtheberge** [comment] 2017-09-15 20:06
@eagoo I'm currently using React with this right now, and I prefer it over react-grid-layout because it uses absolute positioning rather than transformations to move things around, meaning any children with fixed positions aren't thrown off position.

The way you want to set it up is by letting React mount your initial widget(s) to the DOM first through its render, then with the lifecycle method componentDidMount(), initialize your grid with gridstack() and targetting where you want it initialized. 
Example: $(<grid element>).gridstack().

After each time you are adding a widget with React, make sure to then use the API method makeWidget  inside React's lifeycle method componentDidUpdate(), which makes the widget part of the grid directly after React mounts the new widget to the DOM.
Example:  $(<grid element>).data('gridstack').makeWidget($(<element to make>);

When you remove a widget with React, you must first remove it from the grid system with the API method removeWidget. Use the React lifecycle method componentWillUpdate() for this to ensure that you properly remove the item from the grid system before React deletes it from the DOM.
Example:  $(<grid element>).data('gridstack').removeWidget($(<element to remove>));

I hope this was helpful for anyone wishing to incorporate this great plugin with React.

@radiolips I don't have an easy to read example currently, but I might be able to come up with something in the future if you need it. The setup shouldn't be too complex.

**Comment by ramigg** [comment] 2017-09-27 15:37
@derwaldgeist thanks for your effort releasing V1.0. I'm working on a project based on react. Is it possible to use the develop branch right now without the jquery dependency?

**Comment by derwaldgeist** [comment] 2017-09-27 20:47
@ramigg I'm not the maintainer, just a potential user :-)

**Comment by ramigg** [comment] 2017-09-28 06:08
@derwaldgeist my mistake :) 
I meant @radiolips - thanks for your efforts, please answer my question above.

**Comment by funkytek** [comment] 2017-10-09 19:07
@jtheberge can you provide a gist or simple example repo of this working would be helpful

**Comment by radiolips** [comment] 2018-05-02 13:09
Closing this ticket, but if someone gets in touch with me with a good react example, I'd be happy to link to it in the README. @ramigg this is obviously a very late response, but the 1.0 code isn't here. There will be a 0.x release probably this weekend, and I'll begin to get back on the 1.0 bandwagon.

**Comment by Inder2108** [comment] 2020-06-02 09:46
Please refer this repo: https://github.com/Inder2108/react-gridstack-example
It may not be the ideal solution but works fine without any extra node package.

**Comment by adumesny** [comment] 2020-06-02 19:23
Thank you, will take a look!

**Comment by adumesny** [comment] 2020-11-14 02:04
@Inder2108 could you modify your example with gridstack 2.2 which you can now 
```js
import { GridStack } from 'gridstack';
import 'gridstack/dist/gridstack.css';
```
and use npm package instead of CDN ?

**Comment by Inder2108** [comment] 2020-11-17 06:50
The example app (https://github.com/Inder2108/react-gridstack-example) is now updated to use imports instead of CDN urls in index.html. The example uses "useEffect" instead of "componentDidMount" and other lifecycle hooks as mentioned in @jtheberg 's example above.

**Comment by adumesny** [comment] 2020-11-17 17:28
@Inder2108 thanks for the update - wondering why you didn't use 'componentDidMount' instead... and would be great to get a more complete example than just init() - adding widget and tracking changes, etc...

**Comment by Inder2108** [comment] 2020-11-18 14:39
I had a functional component in my case so used useEffect - since "componentDidMount" is available for Class based React Components. Will update the example for both "useEffect" and "componentDidMount" soon.

**Comment by ZachSAEON** [comment] 2020-12-09 11:00
> grid.makeWidget(<element to make>);

Thank you - that's quite a helpful pointer. Before reading this I was trying to figure out why just mapping grid-stack-items inside the gridstack container didn't work as expected

I'm struggling to make this work with a controlled component (where the items are received as props). Do you have any pointer?

**Comment by ZachSAEON** [comment] 2020-12-09 14:22
An example based on the post by jtheberge above:

```js
import { useEffect, createRef, useRef } from 'react'
import 'gridstack/dist/gridstack.min.css'
import { GridStack } from 'gridstack'
import 'gridstack/dist/h5/gridstack-dd-native'

export default ({someArray}) => {
  const refs = useRef({})
  
  if (Object.keys(refs.current).length !== someArray.length) {
    someArray.forEach(({ id }) => {
      refs.current[id] = refs.current[id] || createRef()
    })
  }

  useEffect(() => {
    const grid = GridStack.init()
    grid.removeAll(false)
    someArray.forEach(({ id }) => {
      grid.makeWidget(refs.current[id].current)
    })
  }, [someArray])

  return (
    <div className="grid-stack">
      {someArray?.map((item, i) => {
        return (
          <div
            ref={refs.current[item.id]}
            key={item.id}
            className={clsx('grid-stack-item', 'debug')}
            gs-w="12"
          >
            <div className="grid-stack-item-content">
              <Item {... etc} />
            </div>
          </div>
        )
      })}
    </div>
  )
}
```

**Comment by adumesny** [comment] 2020-12-09 18:14
@ZachSAEON do you mind updating https://github.com/gridstack/gridstack.js/blob/develop/demo/react.html in a code review instead ?

**Comment by zachsa** [comment] 2020-12-10 04:49
Hi. I'm not sure what you mean by a code review, I added a hooks example to the demo folder. It does not completely work as intended though, since removing all widgets and re-adding elements as widgets sometimes changes the user-order

```js
  useEffect(() => {
    const grid = GridStack.init()
    grid.removeAll(false)
    someArray.forEach(({ id }) => {
      grid.makeWidget(refs.current[id].current)
    })
  }, [someArray])

Is it possible to check if a dom node has already been made into a widget? This seems like it might be a better idea:

```js
  useEffect(() => {
    const grid = GridStack.init()
    items.forEach(({ id }) => {
      if (!grid.getWidgetById(refs.current[id].current)) {
        grid.makeWidget(refs.current[id].current)
      }
    })
  }, [items])
```

**Comment by adumesny** [comment] 2020-12-10 05:32
oh I didn't see this before your review. Yep all issues you brought up here I commented on them...

**Closed** 2021-02-28 05:11 UTC
Labels: type:question

**Comment by qlibp** [comment] 2021-07-31 02:37
version: "gridstack": "^4.2.6"

not able to run the example code shown in 
- https://gridstackjs.com/demo/react.html
- https://github.com/Inder2108/react-gridstack-example/blob/master/src/App.js

And I finally found out a work around:
```
// import { GridStack } from 'gridstack'; // not work
import GridStack from '../node_modules/gridstack/dist/gridstack-h5'; // work
```
Not sure why this happen.
