### ISSUE TITLE
v5.1 regression: DnD Snap to Animation

### ISSUE THREAD

**Issue by edancanning** [gridstack/gridstack.js#1973] opened 2022-06-02 21:12 UTC
## Subject of the issue

Snap back to place animation bug - Could be related to [this issue](https://github.com/gridstack/gridstack.js/issues/1966)

![ezgif-4-340732a994](https://user-images.githubusercontent.com/19144364/171738107-0f87833e-ba44-405a-aab8-d426bd215d03.gif)

## Your environment
Current [Demo Env](https://gridstackjs.com/demo/two.html)
- "gridstack": "^5.0.0",
- H5 DnD
- MacOS, Chrome 102.0.5005.61 

## Steps to reproduce

1. Navigate to [two grid demo](https://gridstackjs.com/demo/two.html)
2. Drag element slightly away from the location it's on
3. I think the mouse must be outside the dotted box marking the original location
4. Let go of drag
5. Watch animation bug back to place

<img width="563" alt="Screen Shot 2022-06-02 at 2 08 41 PM" src="https://user-images.githubusercontent.com/19144364/171738699-4f1892ac-be9e-442a-bf99-8072f810d0a2.png">

## Expected behavior
Snap to place without animation

## Actual behavior
Snaps to with a weird animation

**Comment by adumesny** [comment] 2022-06-03 19:11
I see comment in there to supposedly prevent this behavior (with a timer), but maybe putting the animation back cause that wrong delay and likely caused by #1966

**Comment by pgalhardo** [comment] 2022-06-09 09:50
For me it looks like this issue is more noticeable in Firefox than it is in Chrome. Any fix or way to mitigate it?

**Comment by adumesny** [comment] 2022-06-09 16:14
well I'm on vacation for next 2 weeks and trying to avoid 'work'... but a donation would be welcomed

**Comment by adumesny** [comment] 2022-06-14 20:30
fixed in next release...

**Closed by adumesny** 2022-06-14 20:30 UTC
Labels: type:bug, severity:low

**Comment by edancanning** [comment] 2022-07-01 22:27
Thank you!
