### ISSUE TITLE
on change event

### ISSUE THREAD

**Issue by jun1432** [gridstack/gridstack.js#911] opened 2018-06-20 09:04 UTC
This is the first time I'm submitting and issue on a particular project on github. I dunno if this is the right place to ask the below confirmation.

I just want to confirm about the on change event on the documentation as it says "Occurs when adding/removing widgets or existing widgets change their position/size" because I experienced that the event is triggered thrice. I just put a console.log to confirm that it was triggered three times when I drag a widget into the grid.

http://www.screencast.com/t/YWfLsETHA

**Comment by oyeaussie** [comment] 2018-06-23 01:05
I've been experiencing the same issue. I am digging through my code to see what could be calling it more than 1 time.

**Comment by radiolips** [comment] 2018-06-23 17:13
That's very weird. Could you provide a fiddle or other example of this? Maybe one of the recent PRs introduced this.

**Comment by oyeaussie** [comment] 2018-06-24 00:49
In my case this seems to be an expected behavior as when I add a new widget, I resize it right after I add it, which causes 2 on change trigger. I'm using 0.3.0 and haven't tried it on latest dev release. @jun1432 see if you are adding another change trigger in your code.

**Comment by jun1432** [comment] 2018-06-25 03:57
Hi Guys,

Forgot to include the version that I used and its gridstack.js 1.0.0-dev. I'm still tracing the code that might caused the triple call on the change event. I will try to set up a fiddle and update you on the progress.

Thanks,

**Comment by jun1432** [comment] 2018-06-26 11:28
Hi Guys,

Just an update it might be that it was caused by the drop function inside droppable grid where it parses the  json text. It added the widget ( trigger 1 ) and remove the clone widget ( trigger 2 ) with the draggable helper: clone and also having the on change event ( trigger 3 ) passes the items to the serializeWidgetMap which serializes the widgets available in the dashboard.

**Comment by adumesny** [comment] 2019-12-21 03:42
I recently checked in #1096 which removes a LOT of the duplicated/unnecessary on change/added/removed events and updated two.html to show longs now!

in the `float: false` case it behaves exactly as expected: 1 drop event (on a change event if adding a widget doesn't go asked) when just 1 event when moving it (no collision), 1 event with mupltiple items (colission) etc... `float: false` will send change for everything if it colides with jsut 1 thing.
`addWidget()` can now be batch processed as well !

check it out and let me know!

**Closed by adumesny** 2019-12-21 03:42 UTC
Labels: type:bug
